routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('tes', function(){
	dd(App\User::find(14)->orphanage);
});

Route::get('command', function() {
    return view('artisan-command');
});

Route::post('execute-command', function(Illuminate\Http\Request $request) {
    $input = $request->all();
    $value = Artisan::call($input['command']);
    $request->session()->flash('output', $value);
    return redirect()->back();
});

Route::get('/checkout', function () {
    return view('checkout');
});

Route::get('/', function () {
    $products = App\Product::paginate(6);
    return view('home', compact('products'));
});
Route::get('home', function () {
    return redirect('/');
});
Route::get('/dashboard', 'HomeController@index');
Route::get('/contact-us', function(){
    return view('contact-us');
});
Route::resource('products', 'ProductController');

Auth::routes();
Route::group(['middleware' => 'auth'], function() {
    Route::resource('orphanages', 'OrphanageController');
    Route::resource('users', 'UserController');
    Route::resource('carts', 'CartController');
	Route::resource('header-transactions', 'HeaderTransactionController');
	Route::resource('detail-transactions', 'DetailTransactionController');
});

resources/views/artisan-command.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="post" action="{{url('execute-command')}}">
		{{csrf_field()}}
		Command <input type="text" name="command" size="100"> <br>
		<input type="submit">
	</form>
	
	<br>
	<div>
		@if(Session::has('output'))
			exit status = {{Session::get('output')}}
		@endif
	</div>
</body>
</html>

resources/views/checkout.blade.php
@extends('layouts.master')

@section('title', 'Checkout')

@section('content')

<section id="content" class="mbtm checkout">
	<section class="container-fluid container">
        <h3>Checkout</h3>
	
		<section class="row-fluid">
            <form id="comments_form">
                <figure class="span4 first">
                    <div class="input_wrapper">
                        <input type="text" name="recipients_name" placeholder="Recipients Name" />
                        <label for="name"> <i class="icon-user"></i> </label>
                    </div>

                    <div class="input_wrapper">
                        <label for="name"> <i class="icon-phone"></i> </label>
                        <input type="text" name="recipients_contact" placeholder="Recipients Contact" />
                    </div>
                    <figure class="">
                        <textarea rows="10" cols="30" placeholder="Shipping Address"></textarea>
                    </figure>

                    <input type="submit" value="Checkout" />

                </figure>

                <figure class="span8">
                    <p>After checkout, you have to transfer yhe payment to account 527111111 (Nirwan)</p>
                    <p>You will be confirmed when item has been sent to the address you provide.</p>
                </figure>
            </form>
		</section>
	</section>

</section>
<!-- Page Content Container -->
	 

@endsection

resources/views/contact-us.blade.php
@extends('layouts.master')

@section('title', 'Detail')

@section('content')

<!-- Page Content Container -->
<section id="content" class="mbtm product_detal">
	<section class="container-fluid container">

		<section class="row-fluid">
			@if(Session::has('message'))
				<div class="alert alert-success">
	                <button type="button" class="close" data-dismiss="alert">×</button>
	                <p>{{session('message')}}</p>
                </div>
			@endif
		</section>

		<section class="row-fluid">
			<!-- <section id="contact_form" class="span6 form">
				<h3> Contact Form </h3>
				<p> Thank you for visiting our website. Please fill out the following form to request information about our products or to provide feedback about our site. When you are finished, click the ‘Submit’ button to send us your message. </p>
				
				<form method="post" action="contact.php">
					<input type="text" value="Enter Your Name" name="name" required/>
					<input type="email" value="Email Address" name="email" required />
					<textarea name="comments" cols="10" rows="10" required> Enter your Comment</textarea>
					<input type="submit" class="btns" value="Submit" name="submit" />
				</form>
			</section> -->
		
			<section id="contact_info" class="span6 contact_info">
				<h3> Contact Information </h3>

				<figure class="span12 first">
					<p>Thank you for visiting our website. If you have any question, you can contact us through the email.</p>
				</figure>
				
				<figure class="span12 first"> <i class="icon-mobile-phone"></i> admin@forphania.com</figure>
				
				<figure class="span12 first"> <i class="icon-envelope-alt"></i> 082210480625 </figure>
					
					<figure class="span12 first"> 
					<div class="span12 fisrt">
					<i class="icon-map-marker"></i> 
					Jalan Anggrek Cakra, Kemanggisan, Jakarta Barat<br />
	 				</div>
					</figure>
	 

					<!-- <figure id="n_social" class="span12 first"> 
					
						<a href="#"> <i class="icon-facebook"></i> </a> 
						<a href="#"> <i class="icon-twitter"></i> </a> 
						<a href="#"> <i class="icon-google-plus"></i> </a> 
						<a href="#"> <i class="icon-linkedin"></i> </a> 
						<a href="#"> <i class="icon-pinterest"></i> </a> 
						
					
					</figure> -->
					
			</section><!-- /.contact_info -->
		</section><!-- /.row-fluid -->
	</section><!-- /.container-fluid -->

</section>
<!-- Page Content Container -->
@endsection

@push('scripts')

@endpush

resources/views/home.blade.php
@extends('layouts.master')

@section('title', 'Store')

@section('content')

<!-- Page Content Container -->
<section id="content" class="product_grid">
	<section class="container-fluid container">
		<section class="row-fluid">
			<section class="span10 product_view" id="product_grid">  
			@foreach($products->chunk(3) as $productRow)
				@foreach($productRow as $product)
					<figure class="span4 @if($loop->first) first @endif" id="product"> 
						<div class="product_img">
							<a href="{{route('products.show', $product->id)}}"><img src="{{asset($product->image_url)}}" alt="{{$product->name}}" /></a>
						</div>
						<div class="first product_description">
							<h3> <a href="{{route('products.show', $product->id)}}"> {{$product->name}}</a> </h3>
							<p>Panti Asuhan: {{$product->orphanage->name}}</p>
							<span class="price"> Rp{{$product->price}} </span>
							<a href="{{route('products.show', $product->id)}}" class="btn pull-right"> <i class="icon-shopping-cart"></i> </a>
						</div>
					</figure>
				@endforeach
				<hr />
			@endforeach
			</section>
		</section>
		<section class="row-fluid">
			{{$products->links('vendor.pagination.custom')}}
		</section>
		
	</section>
</section>

<!-- Page Content Container -->
@endsection