routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('tes', function(){
	dd(App\User::find(14)->orphanage);
});

Route::get('command', function() {
    return view('artisan-command');
});

Route::post('execute-command', function(Illuminate\Http\Request $request) {
    $input = $request->all();
    $value = Artisan::call($input['command']);
    $request->session()->flash('output', $value);
    return redirect()->back();
});

Route::get('/checkout', function () {
    return view('checkout');
});

Route::get('/', function () {
    $products = App\Product::paginate(6);
    return view('home', compact('products'));
});
Route::get('home', function () {
    return redirect('/');
});
Route::get('/dashboard', 'HomeController@index');
Route::get('/contact-us', function(){
    return view('contact-us');
});
Route::resource('products', 'ProductController');

Auth::routes();
Route::group(['middleware' => 'auth'], function() {
    Route::resource('orphanages', 'OrphanageController');
    Route::resource('users', 'UserController');
    Route::resource('carts', 'CartController');
	Route::resource('header-transactions', 'HeaderTransactionController');
	Route::resource('detail-transactions', 'DetailTransactionController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public function orphanage()
    {
        return $this->belongsTo('App\Orphanage');
    }

    public function carts()
    {
        return $this->belongsToMany('App\Cart');
    }

    public function detail_transactions()
    {
        return $this->hasMany('App\DetailTransaction');
    }

    public function reviews()
    {
        return $this->hasMany('App\Review');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/products/show.blade.php
@extends('layouts.master')

@section('title', 'Detail')

@section('content')

<!-- Page Content Container -->
<section id="content" class="mbtm product_detal">
	<section class="container-fluid container">
	
		<section class="row-fluid">
			@if(Session::has('message'))
				<div class="alert alert-success">
	                <button type="button" class="close" data-dismiss="alert">×</button>
	                <p>{{session('message')}}</p>
                </div>
			@endif
		</section>

		<section class="row-fluid">
			<figure class="span5 first" id="product_image">
				<div class="pro_img" id="pro_img">
					<img src="{{asset('images/wayang-detail.jpg')}}" alt="Default image" /> 
				</div>
			</figure>
				
			<figure class="span7" id="product_info">
				<h3>{{$product->name}}</h3>
				
				<div class="price_holder"> 
					<span class="current_price"> Price: Rp {{$product->price}}</span>
				</div>
				
				<div class="description_holder"> 
					{{$product->description}}
				</div>
					
				<ul class="stock_status">
					<li> Stock: 10 </li>
				</ul>
					
				<figure id="n_social" class="product_detail_social"> 
					<span class="span6">
						<!-- {{$product->reviews->count()}} Reviews -->
					</span>

					<figure class="span6" id="proudct_options">
						<form action="{{route('carts.store')}}" method="POST">
							{{csrf_field()}}
							@if($errors->has('product_id'))
								{{$errors->get('product_id')}}
							@endif
							<input type="hidden" name="product_id" value="{{$product->id}}">				
							<button> Add to <i class="icon-shopping-cart"></i> </button>
						</form>
					</figure>
				</figure>

			</figure>

			<figure class="span12 first" id="product_information">
				<div class="span4 first">
					<h3> Orphanage Information </h3>
					<div class="" id="accordion2">
						<ul class="product_properties">
							<li> <i class="icon-chevron-right"></i> Orphanage Name: {{$product->orphanage->name}}</li>
							<li> <i class="icon-chevron-right"></i> Orphanage Address: {{$product->orphanage->address}}</li>
						</ul>
					</div>
				</div>
				
				<!-- <div class="span8">
					<ul id="comments">
						@forelse($product->reviews as $review)
							<li> 
								<div class="span12 inner"> 
									<h3>{{$review->user->name}}</h3>
									<p>{{$review->content}}</p>
									<p> {{$review->created_at}}</p>
								</div>
							</li>
						@empty
							<li> 
								<div class="span12 inner"> 
									This Product does not have any review yet, Be first to give the review.
								</div>
							</li
						@endforelse
						<li>
							<div class="inner">
								<h3> Leave Review </h3>
								@if(Auth::guest())
									<textarea class="span12 disabled" disabled placeholder="You have to Login to write reviews"></textarea>
								@else
									<form action="" method="POST">
										{{csrf_field()}}
										<textarea class="span12" placeholder="Write your review to this product" name="review_content"></textarea>
										<button class="view_posts pull-right" href="#"> Submit Review </button>
									</form>
								@endif
							</div>
						</li>
					</ul>
				</div> -->
				
			</figure>
		</section>
	</section>

</section>
<!-- Page Content Container -->
@endsection

@push('scripts')
<script>
	
</script>
@endpush